### ISSUE TITLE
Why not support the MAC version?

### ISSUE THREAD

**Issue by AsteriskZuo** [swl-x/MystiQ#104]
Why not support the Mac version？I need source compile by self？

**Comment by AsteriskZuo** [comment]
1.fix bug for save settings:
void ExePath::loadSettings()
{
    QSettings settings;
    QStringList childList = settings.childKeys();
    QStringList groupList = settings.childGroups();
    foreach (QString group, groupList) {
        if ("exepath" == group) {
            settings.beginGroup(group);
            QStringList childList = settings.childKeys();
            foreach (QString name, childList) {
                QString path = settings.value(name).toString();
                program_path[name] = path;
            }
            settings.endGroup();
        }
    }
}
2.fix support mac in pro file
    macx {
        message("macx")
        SOURCES -= services/powermanagement-dummy.cpp
        SOURCES += services/powermanagement-macx.cpp
    } else {
        message("linux")
        SOURCES -= services/powermanagement-dummy.cpp
        SOURCES += services/powermanagement-linux.cpp
    }

**Comment by AsteriskZuo** [comment]
3.After a successful conversion, there is always a popover, and more than one.

**Comment by llamaret** [comment]
> 3.After a successful conversion, there is always a popover, and more than one.

Hello
Are you testing in macOS????
We need a macOS packager in our team

**Comment by llamaret** [comment]
> Why not support the Mac version？I need source compile by self？

We are looking for a packer for MAC. Do you know how to compile from sources and package? You could be the packager we're looking for.

**Comment by llamaret** [comment]
> 3.After a successful conversion, there is always a popover, and more than one.

Fixing

On Windows and GNU / Linux it works fine. In GNU / Linux we use libnotify so that notifications come out in the background in a subtle way. But in MAC we were not clear about the behavior and we had not had a user with MAC to test. Already with this report of yours, it is clear to me. I'm already modifying it so that in MAC only the final notification comes out when converting the last item in the conversion list

**Comment by llamaret** [comment]
> void ExePath::loadSettings()
> {
>     QSettings settings;
>     QStringList childList = settings.childKeys();
>     QStringList groupList = settings.childGroups();
>     foreach (QString group, groupList) {
>         if ("exepath" == group) {
>             settings.beginGroup(group);
>             QStringList childList = settings.childKeys();
>             foreach (QString name, childList) {
>                 QString path = settings.value(name).toString();
>                 program_path[name] = path;
>             }
>             settings.endGroup();
>         }
>     }
> }

I like it

**Comment by AsteriskZuo** [comment]
> > void ExePath::loadSettings()
> > {
> > QSettings settings;
> > QStringList childList = settings.childKeys();
> > QStringList groupList = settings.childGroups();
> > foreach (QString group, groupList) {
> > if ("exepath" == group) {
> > settings.beginGroup(group);
> > QStringList childList = settings.childKeys();
> > foreach (QString name, childList) {
> > QString path = settings.value(name).toString();
> > program_path[name] = path;
> > }
> > settings.endGroup();
> > }
> > }
> > }
> 
> I like it, but, the other way we use now works fine on GNU / Linux and Windows. Doesn't it work well on MAC?
> 
> > void ExePath::loadSettings()
> > {
> > QSettings settings;
> > foreach (QString name, program_path.keys()) {
> > QString path = settings.value("exepath/" + name
> > , program_path[name]).toString();
> > program_path[name] = path;
> > }
> > }

yes, origin code is not work normally。

I'm sorry to have kept you waiting so long. I do use your product on the MAC. I like it, and I'd like to help you improve it on the MAC.

**Comment by AsteriskZuo** [comment]
I need some time to improve the product on the MAC, report some bugs, fix it, pull requset to you.

**Comment by AsteriskZuo** [comment]
I had pull request it
