### ISSUE TITLE
build fails with error  -  recipe for target 'mainwindow.o' failed

### ISSUE THREAD

**Issue by muralikodali** [swl-x/MystiQ#107]
build fails with following error:

In file included from ui/mainwindow.cpp:20:
./ui_mainwindow.h: In member function ‘void Ui_MainWindow::setupUi(QMainWindow*)’:
./ui_mainwindow.h:91:25: error: ‘class QAction’ has no member named ‘setShortcutVisibleInContextMenu’
   91 |         actionAddFiles->setShortcutVisibleInContextMenu(false);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:1007: recipe for target 'mainwindow.o' failed
make: *** [mainwindow.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by llamaret** [comment]
> build fails with following error:
> 
> In file included from ui/mainwindow.cpp:20:
> ./ui_mainwindow.h: In member function ‘void Ui_MainWindow::setupUi(QMainWindow*)’:
> ./ui_mainwindow.h:91:25: error: ‘class QAction’ has no member named ‘setShortcutVisibleInContextMenu’
> 91 | actionAddFiles->setShortcutVisibleInContextMenu(false);
> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Makefile:1007: recipe for target 'mainwindow.o' failed
> make: *** [mainwindow.o] Error 1
> make: *** Waiting for unfinished jobs....

Please tell me which version of Qt you used for compilation and on what operating system.

**Comment by muralikodali** [comment]
qtdiag gave version as :

Qt 5.9.5 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.4.0) on "xcb" 
OS: Ubuntu 18.04.4 LTS [linux version 5.3.0-45-generic]

full log attached for reference.

[qtversion.log](https://github.com/swl-x/MystiQ/files/4413853/qtversion.log)
