### ISSUE TITLE
Enable saving custom user presets

### ISSUE THREAD

**Issue by RattusSolarus** [swl-x/MystiQ#116]
I've been doing a bunch of recoding lately and use a minor modification of an existing preset, but have to make that modification in the Advanced tab for every new batch loaded.
It would be really nice for users to be able to save custom presets to add to the default ones.

Nice application btw. It makes it straightforward to do things that are confusing in others.

**Comment by seigneurfuo** [comment]
Same case for me. Custom user presets will be very useful to me.
I have store a lot of ffmpeg command lines and this feature will allow me to create custom presets for each one..

**Comment by seigneurfuo** [comment]
Duplicate of #105

**Comment by RattusSolarus** [comment]
Apologies for opening duplicate issue. I thought I had scanned existing ones but guess I failed.
