### ISSUE TITLE
Missing 'deb' in INSTALL instructions to add repository for Ubuntu 20

### ISSUE THREAD

**Issue by wildergonzo** [swl-x/MystiQ#128]
**Describe the bug**
In install file: https://github.com/swl-x/MystiQ/blob/master/INSTALL line 90, missing 'deb' in the suggested command to add the repository to list.

**Current:**
`sudo sh -c "echo 'https://download.opensuse.org/repositories/home:/llamaret/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/home:llamaret.list"`

**Expected:**
`sudo sh -c "echo 'deb https://download.opensuse.org/repositories/home:/llamaret/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/home:llamaret.list"`

**Comment by lfdominguez** [comment]
Closes as #136
