### ISSUE TITLE
Create a .deb file to release and optionally export to launchpad PPA

### ISSUE THREAD

**Issue by stdevPavelmc** [swl-x/MystiQ#37]
We need to release a .deb file to release to Debian alike distros, main focus will be lastest Ubuntu LTS release

Optionally the .deb file can be uploaded to a Launchpadd PPA for distribution.

**Comment by llamaret** [comment]
We have currently integrated the project into the openSUSE Builder System, which not only allows you to generate repositories for SUSE, but also for other distros. There are already the MystiQ repositories for **Debian 10**, **Testing** and **Sid** and for **Ubuntu 19.04** and **19.10**.
I made some modifications to the makedeb.sh to be able to extract the .dsc file and the source, necessary to generate the repository in OBS. In GUTL I have published an article that clarifies how to integrate the repository into the mirrorlist. And on the official MystiQ website there is an iframe pointing to the origin of these repositories with the explanation included.
