### ISSUE TITLE
Fallo , no inicia Appimage

### ISSUE THREAD

**Issue by dazars1** [swl-x/MystiQ#87]
La AppImage no inicia

System:     Kernel: 5.4.20-1-lts x86_64 bits: 64 Desktop: i3 4.17.1 Distro: Arch Linux 

Esta es la salida cuando se ejecuta desde terminal.

http://paste.c-net.org/PuppetAugust

Si es algo de mi SO, o algo me falta instalar , podrian indicarmelo. Gracias

**Comment by azubieta** [comment]
Hola, gracias por su reporte.
Intenté reproducir el issue en Manjaro pero no lo logré. Quizás pueda indicarme una distribución más cercana al sistema que usted usa para intentar reproducir el error nuevamente.

Saludos

![Screenshot_20200220_220129](https://user-images.githubusercontent.com/1138094/75003199-a44c9d00-542c-11ea-9dc9-ecbdc74ccceb.png)

**Comment by azubieta** [comment]
Duplicado de #88
