### ISSUE TITLE
libqt5opengl5 dependencies needed to package for Debian 10

### ISSUE THREAD

**Issue by SwampRabbit** [swl-x/MystiQ#97]
**Describe the bug**
Packaging for Debian 10 using pbuilder fails with:
**Project ERROR: Unknown module(s) in QT: opengl**

Please add the following to dependencies:
Build Depend - libqt5opengl5-dev
Depend - libqt5opengl5 (>= 5.10.0)

**To Reproduce**
Build Debian 10 package with pbuilder

**Expected behavior**
Successful build

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MX Linux 19.1 (Debian 10)
 - Browser: N/A
 - Version: MystiQ-20.02.18

**Additional context**
I have tested adding the proposed dependencies to the debian/control file and the package successfully builds and installs.

**Comment by llamaret** [comment]
> I have tested adding the proposed dependencies to the debian/control file and the package successfully builds and installs.

Thanks for reporting the error. The detail, referring to the Pull that you have sent (very certain by the way), is that in the control file we are only putting variables, all the dependencies we are declaring in the script https://github.com/swl-x/MystiQ/ blob / master / makedeb.sh and this script builds the DEB package by filling in all the information that is in the control file. Therefore, we are going to add the libqt5opengl5 dependency to that makedeb.sh file

**Comment by SwampRabbit** [comment]
Understood, thank you, I should have dug into it a bit more.

You could remove the makedeb.sh script in leu of a proper debian folder and files.  Using the debian folder would make it quick for any Debian based distro to package it for their repos with sbuild and pbuilder.  This won't affect your OBS builds, although you would have to include the .org.tar.gz, debian.tar.gz, and .dsc file.

In order to package it for our repo I had to create all the files since they were generic.

Your process probably is the best for your automated builds I assume?

Please feel free to close this issue when you want.

**Comment by stdevPavelmc** [comment]
> Understood, thank you, I should have dug into it a bit more.
> 
> You could remove the makedeb.sh script in leu of a proper debian folder and files. Using the debian folder would make it quick for any Debian based distro to package it for their repos with sbuild and pbuilder. This won't affect your OBS builds, although you would have to include the .org.tar.gz, debian.tar.gz, and .dsc file.
> 
> In order to package it for our repo I had to create all the files since they were generic.
> 
> Your process probably is the best for your automated builds I assume?
> 
> Please feel free to close this issue when you want.

Thanks @SwampRabbit for the job, if you take a peek in the https://github.com/swl-x/MystiQ/blob/master/makedeb.sh file you will see that it takes care of build dynamically the .org.tar.gz, debian.tar.gz, and .dsc files; then the .deb file is build on top of that.

That's why we use that script and the var substitution in the `debian/control` file: to automate the process up to the last bit; in that way we can build/test it on any CI/CD env.

Please test that and feel free to patch the script and `debian/control` to adhere to that philosophy and make a new PR.

@llamaret I think we need to update the www and other infos in there to reflect the new site and other things...

**Comment by SwampRabbit** [comment]
@stdevPavelmc and @llamaret  thank you again, I will be taking your advice as soon as I get time.
I think your makedeb.sh is great, but I also need to talk to our packaging lead, because we package in a chroot (sbuild or pbuilder).

I don't want to affect your CI/CD env here, so if I have to package it differently that is ok too.
